### ISSUE TITLE
related service requests modal dialog issue in admin portal (V1.4.0)

### ISSUE THREAD

**Issue by ying-pbrc** [sparc-request/sparc-request#126]
It wasn't working on my machine (see attached screenshot). I am not sure if this was something I missed during merge process. Have you seen this problem?   
![related servce requires- modal dialog not working](https://cloud.githubusercontent.com/assets/7648699/8987212/7c2e95e8-36a5-11e5-9cf5-07e571aca5d4.png)

**Comment by robertjamesmiller** [comment]
I'm experiencing this issue too.

**Comment by ying-pbrc** [comment]
Thanks for your confirmation. I just saw this few moments ago, other modals seem to be working fine.

**Comment by ying-pbrc** [comment]
Rob,
Is it also an issue on your dev or test serviers? or it’s only in the development environment?

**Comment by robertjamesmiller** [comment]
I confirmed it on our test server.

**Comment by ying-pbrc** [comment]
This issue only arises when use_epic is being turned off, in that case, I saw the following error:
FormFxManager.getSelector: could not find element for key #study_type_answer_higher_level_of_privacy_answer

The modal in the Related Service Requests tab works again after I commenting out study_type_answer related code (Lines: 46-51) in 
 app/assets/jhavascripts/portal/studies.js.coffee.

Is there a better way to fix this? Thanks.
