### ISSUE TITLE
application.yml.example missing

### ISSUE THREAD

**Issue by heathharrelson** [sparc-request/sparc-request#1544]
I'm trying to set up an instance for evaluation at my institution for evaluation. While reviewing `multi_institutional_documentation.md`, I noted that the file `config/application.yml.example` is missing. This file seems to have been removed in release 3.0.1:

https://github.com/sparc-request/sparc-request/tree/v3.0.0/config
https://github.com/sparc-request/sparc-request/tree/v3.0.1/config

If this is an oversight, the file should probably be restored. If it was done intentionally, the documentation shouldn't reference the file.

**Comment by kyle-glick** [comment]
@heathharrelson 

The `multi_institutional_documentation.md` was just updated on the current development branch v3.4.0 to reflect the changes made to move the contents of `application.yml` and various other config files to the `settings` table.

I would recommend following the docs on `v3.4.0` for now.

**Comment by kyle-glick** [comment]
@heathharrelson 

While looking at the docs, I realized that some important information about PermissibleValues was omitted. See https://github.com/sparc-request/sparc-request/pull/1552/files for how to seed and create your Permissible Values.

**Comment by kyle-glick** [comment]
@heathharrelson 

See https://github.com/sparc-request/sparc-request/pull/1557 for an updated version of the 3.3.0 Settings docs. I hope it helps!
