### ISSUE TITLE
Incorrect Instructions for Requiring initial_cm_creation in Documentation

### ISSUE THREAD

**Issue by heathharrelson** [sparc-request/sparc-request#1545]
Several documentation files reference how to require `initial_cm_creation.rb`, but the path listed is incorrect (`require 'lib/initial_cm_creation'` instead of `require 'app/lib/initial_cm_creation'`): 

```
$ rails c
Loading development environment (Rails 5.2.0)
irb(main):001:0> require './lib/initial_cm_creation'
LoadError: cannot load such file -- /sparc/lib/initial_cm_creation
	from (irb):1
irb(main):002:0> require './app/lib/initial_cm_creation'
=> true
irb(main):003:0> 
```

The incorrect instructions are included in the following places in the source:

* INSTALL.md
* doc/easy_installation.doc
* doc/easy_installation.pdf

And in the wiki:

https://github.com/sparc-request/sparc-request/wiki/Deployment

**Comment by kyle-glick** [comment]
These changes have been made to all 4 locations. Closing this issue.
