### ISSUE TITLE
Requests missing from UI on SPARCRequest 3.5.0 upgrade from 3.3.0

### ISSUE THREAD

**Issue by wsams** [sparc-request/sparc-request#1945]
Recently we upgraded SPARCRequest to 3.5.0 from 3.3.0. A user reported that requests are missing, but after closer inspection, they're only missing from the UI. (In most cases, there are a couple protocols with requests showing in the UI, but the majority are missing. Maybe 2 of 28 protocols are showing requests. I restored our 3.3.0 instance from backups and performed the upgrade locally and ran into the same issue just to confirm.

For example,

If we navigate to SPARCDashboard and click **Requests**, the list appears empty,

![Screen Shot 2019-07-29 at 12 29 59 PM](https://user-images.githubusercontent.com/273863/62076742-3f65f700-b1fd-11e9-83cb-3c800c580e39.png)

If we click the Protocol Id link/button, the Requests table on that page is empty as well.

But when we click **Add / Modify Request** we see all of the attached services under **My Services**. For example,

![Screen Shot 2019-07-29 at 12 30 22 PM](https://user-images.githubusercontent.com/273863/62076860-923fae80-b1fd-11e9-8bea-26dc209394d7.png)

**Comment by wsams** [comment]
CC @kirenotneb @heathharrelson

**Comment by WenjunHe1027** [comment]
Hi Weldon,

Were the 2 screenshots you used taken from the same protocol?

We haven't seen any issue like this with the release updates from v3.3.0 to 3.5.0. However, there is one feature change that we did in v3.4.0 which added an attribute for super users to be chosen to have "Access to Empty Protocols" or not, see item#43 on the SRv3.4.0 new features document:
https://sparcrequest.atlassian.net/wiki/spaces/Release/pages/228687873/SPARCRequest+Version+3.4.0+SPARCFulfillment+Version+2.8.5

Please confirm whether it is caused by that? 
If not, did you have other customizations with your application that could be related?

Wenjun He @ SPARC MUSC Team

**Comment by wsams** [comment]
Hi @WenjunHe1027 , thanks for the quick reply.

I think those screenshots were from the same protocol, but if not the behavior is still the same. I double checked.

> Were the 2 screenshots you used taken from the same protocol?

I believe I had that flag checked, but just to confirm I made myself a super user for every organization and set "Access to Empty Protocols" to 1 in each. But I'm still missing those rows.

> Please confirm whether it is caused by that?

I don't believe we have any customizations yet.

> If not, did you have other customizations with your application that could be related?

**Comment by WenjunHe1027** [comment]
1).FYI, You only need to add "Access to Empty Protocols" of a super user on 1 of the organizations for it to work.
 
2). Was there any migration errors when you upgraded your version? Please refer to the rake tasks list in the v3.3.0 and v3.4.0 release documents for the necessary rake tasks and environment/setting changes involved:
https://sparcrequest.atlassian.net/wiki/spaces/Release/pages/157941763/SPARCRequest+Version+3.3.0+SPARCFulfillment+Version+2.8.0
https://sparcrequest.atlassian.net/wiki/spaces/Release/pages/228687873/SPARCRequest+Version+3.4.0+SPARCFulfillment+Version+2.8.5


3). Are you also using SPARCFulfillment?
If so, please also check on the new setting fulfillment_contingent_on_catalog_manager, as well as Ying's PR to see if that's related: https://github.com/sparc-request/sparc-request/pull/1885/files

Wenjun

**Comment by wsams** [comment]
Hi @WenjunHe1027 ,

This is good to know, thanks for the tip.

> 1).FYI, You only need to add "Access to Empty Protocols" of a super user on 1 of the organizations for it to work.

I didn't see any errors on `db:migrate` going from 3.3.0 to 3.5.0, or any of the other tasks. This morning I looked over the release docs for 3.3.0 and 3.4.0. I wasn't involved in setting up 3.3.0, but when I tried to run `migrate_ids_to_bigint` it failed with,

```
rails aborted!
ActiveRecord::ActiveRecordError: No such column: arms.sparc_id
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:606:in `column_for'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:668:in `change_column_for_alter'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:371:in `change_column'
```

It doesn't look like we need to do anything for 3.4.0 at this time.

> Was there any migration errors when you upgraded your version?

We just set up SPARCFulfillment 2.9.0 this past month. I tried both true and false for `fulfillment_contingent_on_catalog_manager` without any changes to behavior.

> 3). Are you also using SPARCFulfillment?

The last protocol I tried to add a request on threw this error. I've been seeing this sort of error in other locations. It looks like the Identity is Nil. I've seen `full_name` and some of the other identity methods fail. Not sure if it's related or not.

![Screen Shot 2019-07-30 at 10 34 40 AM](https://user-images.githubusercontent.com/273863/62152167-d6db5080-b2b6-11e9-98ad-4b9d3cddc9bd.png)

**Comment by wsams** [comment]
Hi @WenjunHe1027 . I've been out of office a few days, but yesterday I took a different approach and upgraded from 3.3.0 to 3.4.0. Previously we jumped straight to 3.5.0. This appears to have resolved the issue with missing requests, at least in 3.4.0. I think we can go ahead and close this issue unless it pops up when I do the 3.5.0 upgrade. Thanks again for your help.
