### ISSUE TITLE
Lost changes from pull request "Override images css locale constants emails"

### ISSUE THREAD

**Issue by robertjamesmiller** [sparc-request/sparc-request#27]
Please delete the following file because it should no longer be used:
sparc-request/app/views/layouts/portal/_header.html.haml

and then update this file to reference the shared/header_logos file:
/app/views/layouts/portal/application.html.haml

These changes were a part of this pull request: https://github.com/sparc-request/sparc-request/pull/10/files

Everything else looks great, thanks.

**Comment by robertjamesmiller** [comment]
This week, I'll create a pull request to fix this unless you're planning to do it at MUSC.

**Comment by amcates** [comment]
Thanks!  We just cleared all previous pull requests

**Comment by robertjamesmiller** [comment]
I'm working on our pull request for this and wanted to mention that we don't want bootstrap classes on images, just the text, so the following is two lines instead of one line:
              .return-to-previous
                = navigation_link image_tag('GoBack.png'), @back
                = navigation_link t(:bottom_navigation)[:go_back], @back, "btn btn-success btn-lg"

Also, I think it would be good if all new "buttons" (e.g., "Create New Study") were text annotated with CSS (to create the button look) instead of using an image; that way it will be easy for institutions to customize buttons via the locale file. what do you think?

**Comment by amcates** [comment]
I agree, I believe we only went the image route because it was the easiest way.  We used mockups to create most of the layout.  Is this issue addressed in your current pull requests?

**Comment by robertjamesmiller** [comment]
yes, my pull request separates images from text so that we can style the text as a bootstrap button. this separation should not affect your display.
