### ISSUE TITLE
styles need clean up

### ISSUE THREAD

**Issue by loganfreeman** [sparc-request/sparc-request#310]
why the styles have sass, scss, and css? can you consolidate into one syntax?

**Comment by jleonardw9** [comment]
That is one of the upgrades we are trying to currently work towards. Any help would be appreciated.

**Comment by loganfreeman** [comment]
I converted all the sass into scss. it works fine. I use bootstrap + sass, and use the syntax scss. You have two styles: one for the portal, one for non-portal. If you use scss, it should help you a lot.

**Comment by jleonardw9** [comment]
@loganfreeman Feel free to put in a pull request if you're interested in getting your code pulled into the main project.
