### ISSUE TITLE
selected for epic validation error

### ISSUE THREAD

**Issue by ying-pbrc** [sparc-request/sparc-request#535]
![selected for epic error from dashboard](https://cloud.githubusercontent.com/assets/7648699/16433808/a77e1a9e-3d51-11e6-9fcb-336844d929b8.jpg)
![step 1 error when epic is turned off](https://cloud.githubusercontent.com/assets/7648699/16433814/ab0a231a-3d51-11e6-811d-6ec34bda41e9.jpg)

**Comment by amcates** [comment]
Thank you Ying for the pull request.  We have accepted your pull request.
