### ISSUE TITLE
date fields not working on dashboard study form 

### ISSUE THREAD

**Issue by ying-pbrc** [sparc-request/sparc-request#555]
Specifically, 
(Potential) Funding Start Date - not saving
IRA Approval Date - not  saving
IRA Expiration Date - not  saving
IACUC Approval Date - saved, but not showing when edit
IACUC Expiration Date - saved, but not showing when edit

**Comment by amcates** [comment]
Thanks Ying,  I believe this branch will fix the issue.  A pull request
will go out once the specs pass on travis.

**Comment by ying-pbrc** [comment]
issue resolved in v1.8.0
