### ISSUE TITLE
Pricing map is_one_time_fee incorrectly being set to false

### ISSUE THREAD

**Issue by robertjamesmiller** [sparc-request/sparc-request#66]
Situation: a service has one pricing map with "is_one_time_fee" set to true. Subsequently, in catalog manager the service is loaded/displayed, no changes made, and then the "Save" button is clicked, after which is_one_time_fee is updated to false. Are you able to recreate this issue?

**Comment by amcates** [comment]
We are looking in to this and will provide feedback shortly

**Comment by jug2** [comment]
I am unable to recreate this issue. I created a service with a new OTF pricing map. Saved. Everything looks good. I reloaded page. Opened pricing map. Didn't make any changes but clicked save again. When I open up the pricing map, OTF is still set as true. Are these the same steps you are following or am I missing something? Thanks.

**Comment by robertjamesmiller** [comment]
We're creating/inserting the services and pricing maps using the following script: https://github.com/sparc-request/sparc-request/blob/master/lib/tasks/import_cores_and_services.rake . If we're creating the service and pricing map outside of catalog manager, is there something we need to do to prevent this issue from happening?

**Comment by jug2** [comment]
Do you have a csv or excel file of the services you’re inserting using the script? If so, can you send me a snapshot of that?
Thanks,
Lane

**Comment by sparc-request** [comment]
Does this happen if you manually create a service in Catalog Manager? Or only for services that are imported and then viewed in Catalog Manager?

Andrew Cates
Ruby Development Manager
Biomedical Informatics Center
Medical University of South Carolina

**Comment by robertjamesmiller** [comment]
Andrew, it also happens when I manually create a service within Catalog Manager.

Lane, I emailed you our services.csv.

**Comment by robertjamesmiller** [comment]
Google Chrome's developers tools are showing the following request parameters, which include "is_one_time_fee" = 0 and, thus, maybe the server side is fine but the request generation/view is not working for us.

utf8:✓
_method:put
authenticity_token:+XjQdAOCtLZSxyxZ5XA17tyosoip3tJWkLOaVYpYjto=
org_unit[id]:927
service[id]:927
service[program]:136
service[core]:285
service[name]:REDCap New Project Request
service[abbreviation]:REDCap New Project Request
service[description]:Request for a new research study  to be created in REDCap today.
service[order]:1
service[is_available]:true
service[cpt_code]:
service[charge_code]:
service[revenue_code]:
service[send_to_epic]:0
pricing_maps[1058][id]:1058
diabled_fields_present:true
pricing_maps[1058][is_one_time_fee]:0
new_rs:New Related Service
commit:Save

**Comment by robertjamesmiller** [comment]
I can see in the Catalog Manager HTML two contradicting inputs (one with a value of "0" and the other with a value of "true"):
<input id="pricing_maps_1053_is_one_time_fee" name="pricing_maps[1053][is_one_time_fee]" type="hidden" value="0">
<input checked="checked" class="otf_checkbox" data-pricing_map_clinical_quantity_type="person" data-pricing_map_id="1053" disabled="disabled" id="otf_checkbox_1053" name="pricing_maps[1053][is_one_time_fee]" readonly="readonly" type="checkbox" value="true">

It seems like line 98 is the culprit: https://github.com/sparc-request/sparc-request/blob/master/app/views/catalog_manager/services/_pricing_map.html.haml
= hidden_field_tag "pricing_maps[#{pricing_map.try(:[], 'id') || 'blank_pricing_map'}][is_one_time_fee]", 0

Should that hidden tag be suppressed for existing pricing maps?

**Comment by robertjamesmiller** [comment]
I've created a pull request for this issue: https://github.com/sparc-request/sparc-request/pull/69 . Please let me know what you think of my code changes.

**Comment by amcates** [comment]
Awesome, thanks!
