### ISSUE TITLE
typo in os## branches

### ISSUE THREAD

**Issue by ying-pbrc** [sparc-request/sparc-request#982]
In db/seeds/permissable_values/2.0.5/document_types.csv, 3rd row, I believe the key for Certificate of Confidentiality should be cofc instead.

**Comment by WenjunHe1027** [comment]
Hi Ying,

Thank you for reporting this.
I have corrected the typo on the os3.0.0 branch 
: https://github.com/sparc-request/sparc-request/commit/13525d3c1c3ea9407eb85ea77528cbc46862119c

<img width="1011" alt="screen shot 2017-08-16 at 2 50 30 pm" src="https://user-images.githubusercontent.com/15877540/29380159-cb31f0fa-8292-11e7-857f-dc41b2792ed3.png">

Wenjun

**Comment by ying-pbrc** [comment]
resolved
